# Generated by Django 6.0 on 2025-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='players/')),
                ('position', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
